### ISSUE TITLE
TextAttack API changed

### ISSUE THREAD

**Issue by einderyl** [Azure/counterfit#13]
Hello, I've just started using this library and things were working for a few days, but I think there's been an API change in TextAttack which broke it (ART works OK).

EDIT: I tried running Counterfit on Colab and the embeddings files now load OK. However, running the moviereviews tutorial (`interact moviereviews`, `use deepwordbug`, `run`) now throw the following exception:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 2063, in onecmd_plus_hooks
>     stop = self.onecmd(statement, add_to_history=add_to_history)
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 2493, in onecmd
>     stop = func(statement)
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/decorators.py", line 318, in cmd_wrapper
>     return func(*args_list, **kwargs)
>   File "/content/counterfit/commands/run.py", line 56, in do_run
>     CFState.get_instance().active_target.run_attack(logging=args.log)
>   File "/content/counterfit/core/targets.py", line 194, in run_attack
>     resulting_samples = self._run_attack(logging)  # call the specific method
>   File "/content/counterfit/core/targets.py", line 306, in _run_attack
>     return self._run_textattack_attack(logging)
>   File "/content/counterfit/core/targets.py", line 296, in _run_textattack_attack
>     results_iter = attack_cls.attack_dataset(
> AttributeError: 'Attack' object has no attribute 'attack_dataset'
> EXCEPTION of type 'AttributeError' occurred with message: 'Attack' object has no attribute 'attack_dataset'
> 

ART runs okay so it looks like it might be one of the new TextAttack API changes.

----

When I try to `load textattack`, it can't find some embeddings files:

> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/alzotolalgo.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/bae.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/bert.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/camrwr.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/deepwordbug.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/improved_ga.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/InputReduction.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/Kuleshov2017.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/pwws.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/textbugger.py: Could not find word_embeddings\paragramcf on server.
> 
> textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.
> 
> [!] Failed to load counterfit/frameworks/textattack/textfooler.py: Could not find word_embeddings\paragramcf on server.
> 
> 
> [+] Framework loaded successfully!

It finishes by saying the library loaded successfully, but `list attacks` gives  

> [!] No frameworks have been loaded. Try 'load <framework>'.

It was working at least 24 hours ago, so it looks like it might be the most recent TextAttack commit.

**Comment by moohax** [comment]
Will take a look and get a fix. 

What OS are you on? It looks to be Windows. TextAttack can't find the path to download because the path that gets passed is incorrect, note the end `word_embeddings\paragramcf`. It should be  `https://textattack.s3.amazonaws.com/word_embeddings/paragramcf`. 

For Windows you need to manually download the paragramcf file and extract it into `c:\users\user\.cache`.

**Comment by einderyl** [comment]
Yup, I'm on Windows, thanks for the embeddings fix!

**Comment by moohax** [comment]
Did that work for you? If so, I'll close the issue.

**Comment by einderyl** [comment]
Yes it worked for me, but the other TextAttack issue (calling it from Counterfit using the moviereviews example) isn't fixed. I'll edit and open a new issue since they don't seem to be related.
