### ISSUE TITLE
AttributeError with moviereviews tutorial

### ISSUE THREAD

**Issue by einderyl** [Azure/counterfit#15]
Running the moviereviews tutorial (`interact moviereviews`, `use deepwordbug`, `run`) throws the following exception:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 2063, in onecmd_plus_hooks
>     stop = self.onecmd(statement, add_to_history=add_to_history)
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 2493, in onecmd
>     stop = func(statement)
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/decorators.py", line 318, in cmd_wrapper
>     return func(*args_list, **kwargs)
>   File "/content/counterfit/commands/run.py", line 56, in do_run
>     CFState.get_instance().active_target.run_attack(logging=args.log)
>   File "/content/counterfit/core/targets.py", line 194, in run_attack
>     resulting_samples = self._run_attack(logging)  # call the specific method
>   File "/content/counterfit/core/targets.py", line 306, in _run_attack
>     return self._run_textattack_attack(logging)
>   File "/content/counterfit/core/targets.py", line 296, in _run_textattack_attack
>     results_iter = attack_cls.attack_dataset(
> AttributeError: 'Attack' object has no attribute 'attack_dataset'
> EXCEPTION of type 'AttributeError' occurred with message: 'Attack' object has no attribute 'attack_dataset'

I get the same error when I try with a different text classifier and dataset, so I think it might be one of the recent TextAttack commits? It ran fine until the first Friday commit. ART still loads and works fine.

**Comment by rdheekonda** [comment]
Hi einderyl,

Thanks for reaching out to us. I tried to reproduce the error but couldn't able to. However, when I ran the above sequence of commands for textattack, the attack was successful.

 `moviereviews> load textattack

[+] Framework loaded successfully!

moviereviews> use deepwordbug

[+] Using deepwordbug 306a9bc4

moviereviews>deepwordbug> run

[+] Running deepwordbug on moviereviews

textattack: Unknown if model of class <class 'counterfit.targets.moviereviews.movie-reviews.MovieReviewsSentimentLSTM'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.
1it [01:07, 67.87s/it]

[+] 1/1 succeeded


     Sample Index      Label (conf)     Attack Label (conf)  % edit dist.  Elapsed Time [sec]    Queries (rate)                                      Attack Input
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1.               0          1 (0.9871)           0 (0.5242)      1.07893%                68.2           384 (5.6   Ever watched a movie that lost the plDt? Well, this didn't eevn really have one
                                                                                                       query/sec)  to begiVn with.<br /><br />Where to begin? The achingly tedious scenes of our
                                                                                                                   heroine sitting around the house with actually no sense of menace or even
                                                                                                                   foreboding created eevn during the apparently constant thunderstorms (that are
                                                                                                                   strangely never actually heard in the house-great double glazing)? The house that
                                                                                                                   the third girl who serves no purpose to the lot except to provide a surprisingly
                                                                                                                   quick gory murder just as the tedium becomes unbearable? Or Heven the beginning
                                                                                                                   which suggests a spate of 20+ killings throughout the area Wven though it is
                                                                                                                   apparent the killer never ventures far from the house? Or the bizarre ritual with
                                                                                                                   the salt & pepper that pretty much sums up most of the films inherent lack of
                                                                                                                   direction.<br /><br />Add a lead actress who can't act but at least is willing to
                                                                                                                   do some completely irrelevant nude shower scenes and this video is truOly nasty,
                                                                                                                   but not in the way you hope.<br /><br />Given a following simply for being banned
                                                                                                                   in the UK in the 80's (moGstly because of a final surprisingly over extended
                                                                                                                   murder) it offers nothing but curiosity value- and one classic 'daft' murder
                                                                                                                   (don't worry-its telegraphed at least ten imnutes before).<br /><br />After a
                                                                                                                   walk in the woods our victim comes to a Uather steep upward slope which they
                                                                                                                   obviously struggle up. Halfway through they see a figure at the top dressed in
                                                                                                                   black and brandishing a large scythe. What do they do? Slide down and run like
                                                                                                                   the est of us? No, of course not- they struggle to the top and stand conveniently
                                                                                                                   nice and upright in front of the lurder weapon.<br /><br />It really IS only a
                                                                                                                   movie as they asy..`

Could you downgrade `textattack==0.2.15` using the command `pip install textattack==0.2.15`?

Thanks,
MS Counterfit Team

**Comment by einderyl** [comment]
Downgrading the textattack version helped resolve the issue, thanks!
