### ISSUE TITLE
support for non probability outputs

### ISSUE THREAD

**Issue by priamai** [Azure/counterfit#21]
Hi there,
very nice project, is there a plan to implement also attacks that works on the label output (no probabilities) or limited API query setting?
There was an [article here](https://arxiv.org/pdf/1804.08598.pdf) a while ago which would be nice to have.
Is this something that should be implemented in the ART component?

**Comment by priamai** [comment]
Okay maybe I am not interpreting the documentation right, for example the HopSpikJumpAttack works on predicted labels not probabilities, but in the creditfraud example:
https://github.com/Azure/counterfit/blob/main/demo/WEBINAR-DEMO-2.md
the target is designed with out probabilities.
Would be nice to get some clarity there.

**Comment by moohax** [comment]
You effectively translate probabilities to labels depending on what a model gives you back in `outputs_to_labels`. 

A good example here in the [wiki ](https://github.com/Azure/counterfit/wiki/Advanced-Use#overriding-functions-in-the-parent-target-class). TextAttack requires a numerical value in `model_output_classes`, and ART will work on with a text label of a numerical label.

**Comment by priamai** [comment]
Hi there,
that I understand but is there an example where the target outputs a label (not the probability) ? The creditcard example provides output probabilities.
The HopSkipJump should work directly with binary labels and not probabilities.

**Comment by priamai** [comment]
Will try that thanks.
