### ISSUE TITLE
EXCEPTION of type 'AttributeError' occurred with message: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by lzomlot** [Azure/counterfit#25]
I installed Counterfit using Option 2. While I am going through 'Basic Use' example, I got this Exception. Any suggestions.

 File "C:\.....\Anaconda3\envs\counterfit\lib\site-packages\art\utils.py", line 534, in check_and_transform_label_format
    if len(labels.shape) == 2 and labels.shape[1] > 1:
AttributeError: 'list' object has no attribute 'shape'
EXCEPTION of type 'AttributeError' occurred with message: 'list' object has no attribute 'shape'

**Comment by HuShiyangchn** [comment]
Same problem, it seems that this problem happened when you assgin the attack name when use "scan" command. If you simply use "scan -n 3 --log", it will work. And the "use" and "run" command works for me, so I guess there might be some bugs in scan.py.
![image](https://user-images.githubusercontent.com/55211567/146727340-9b88f6e4-b17a-4352-8a79-d6b0ce7e52f0.png)
![image](https://user-images.githubusercontent.com/55211567/146727362-55554898-b3db-4c21-a861-412200505b7f.png)

**Comment by moohax** [comment]
This is likely due to your `target_output_classes` not being a list, or the return of your predict function not being a list of lists.

**Comment by moohax** [comment]
The return of the predict function should be a list of lists, where each list is the same length as `target_output_classes`
