### ISSUE TITLE
Permission denied inside counterfit Docker container

### ISSUE THREAD

**Issue by RamvigneshPasupathy** [Azure/counterfit#26]
Problem while creating a new target inside a counterfit docker container:

` [!] Failed to write target file: [Errno 13] Permission denied: 'counterfit/targets/dummy'.`

My container is based on the image pulled using `docker pull azuretrustworthyml/counterfit:0.1`

<img src="https://user-images.githubusercontent.com/12979892/140031755-fb08be7f-f033-4b8a-8014-851a389cdc9d.png" width=800 height=350 />

Any help to fix this please..

**Comment by moohax** [comment]
Thank you for this! We're investigating.
