### ISSUE TITLE
Problem running counterfit.py

### ISSUE THREAD

**Issue by Hobstarr** [Azure/counterfit#34]
Hi,

after successfully running the requirements, and loading up the counterfeit environment, I receive the following error when trying to run counterfit.py

'ImportError: cannot import name '_status_message' from 'scipy.optimize.optimize'

Looking to try and fix this and get counterfit running again. This is on a mac. I've tried different versions of scipy, but can't find one that will work with this.

Thanks!

**Comment by moohax** [comment]
I think this has to do with the scipy version. I'm seeing a regression in our `requirements.txt`. Try `pip install scipy==1.4.1`

This [thread](https://github.com/scipy/scipy/issues/10998) suggests reinstalling scipy

**Comment by Hobstarr** [comment]
This completely fixed the problem, thank you very much for the advice. I tried a few versions of scipy but couldn't figure out one that would make it work, this was exactly what I needed.
