### ISSUE TITLE
Error with Anaconda Python environment install

### ISSUE THREAD

**Issue by mikemishal** [Azure/counterfit#56]
Building wheels for collected packages: python-Levenshtein, torchfile, bs4, gym, networkx, clang, future, iopath, pyperclip, termcolor, wrapt, gdown, mpld3, word2number, docopt, sqlitedict, langdetect, wikipedia-api, overrides
  Building wheel for python-Levenshtein (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/__init__.py -> build/lib.linux-x86_64-cpython-38/Levenshtein
      running egg_info
      writing python_Levenshtein.egg-info/PKG-INFO
      writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
      deleting python_Levenshtein.egg-info/entry_points.txt
      writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
      writing requirements to python_Levenshtein.egg-info/requires.txt
      writing top-level names to python_Levenshtein.egg-info/top_level.txt
      reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*pyc' found anywhere in distribution
      warning: no previously-included files matching '*so' found anywhere in distribution
      warning: no previously-included files matching '.project' found anywhere in distribution
      warning: no previously-included files matching '.pydevproject' found anywhere in distribution
      adding license file 'COPYING'
      writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      copying Levenshtein/_levenshtein.c -> build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/_levenshtein.h -> build/lib.linux-x86_64-cpython-38/Levenshtein
      running build_ext
      building 'Levenshtein._levenshtein' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/Levenshtein
      gcc -pthread -B /home/mike/anaconda3/envs/counterfit/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mike/anaconda3/envs/counterfit/include/python3.8 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-cpython-38/Levenshtein/_levenshtein.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-Levenshtein
  Running setup.py clean for python-Levenshtein
  Building wheel for torchfile (setup.py) ... done
  Created wheel for torchfile: filename=torchfile-0.1.0-py3-none-any.whl size=5693 sha256=9ffaf688f6b324ff14fd5d40238bae410d91407f0b3f5135f0fe0aa76a4e3f75
  Stored in directory: /home/mike/.cache/pip/wheels/b9/99/d1/9f3f4411a958a22ccf782e33c7238a07f04a9597f2f3b38792
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1257 sha256=cd3f60c49624cadc73dfc3f026ddfd440a4f79a1e05f3d6c6c7945ad31a21540
  Stored in directory: /home/mike/.cache/pip/wheels/75/78/21/68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
  Building wheel for gym (setup.py) ... done
  Created wheel for gym: filename=gym-0.19.0-py3-none-any.whl size=1663091 sha256=027f153e5fdc6342102d2b0bb5c9d103d27a543c91a640f546a344b3b8a52e88
  Stored in directory: /home/mike/.cache/pip/wheels/11/36/28/628f4dd3779e4037a6fca1aaed76827ffa4315c3ab6bfadcf6
  Building wheel for networkx (setup.py) ... done
  Created wheel for networkx: filename=networkx-2.2-py2.py3-none-any.whl size=1526919 sha256=cd2e280d8fd8582c43bc79c94485f58c4feb27b4caa2ab970623c5a16ebf4074
  Stored in directory: /home/mike/.cache/pip/wheels/c3/d7/dd/7e2e485ecd56541b03075c9e3692ec12f6b43e90d09f9a6a9a
  Building wheel for clang (setup.py) ... done
  Created wheel for clang: filename=clang-5.0-py3-none-any.whl size=30681 sha256=0bc080e6b00b857ac4babf8c1dcb6a5021f7295ab6d5c9cc7201c2b3b50d7876
  Stored in directory: /home/mike/.cache/pip/wheels/f1/60/77/22b9b5887bd47801796a856f47650d9789c74dc3161a26d608
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=578710c9de7bdef01072479ce01ef0c22685cf370074e6572b801d96e661c511
  Stored in directory: /home/mike/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31532 sha256=61864d9531c7806b20d5d8985882381f0d69738c6ff79335e7102c952a4abf21
  Stored in directory: /home/mike/.cache/pip/wheels/89/3e/24/0f349c0b2eeb6965903035f3b00dbb5c9bea437b4a2f18d82c
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11123 sha256=75079a19dea97a998282a18b3e98f63cc32026c1b2bcaa35858de6442e409f95
  Stored in directory: /home/mike/.cache/pip/wheels/7f/1a/65/84ff8c386bec21fca6d220ea1f5498a0367883a78dd5ba6122
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4832 sha256=afabaf04dd54fc73d2bbf7f267f9c090fe51636603bfa401270b3c49db4ec544
  Stored in directory: /home/mike/.cache/pip/wheels/a0/16/9c/5473df82468f958445479c59e784896fa24f4a5fc024b0f501
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-py3-none-any.whl size=19553 sha256=7c03d30f68b6abd56dfd6b224a02cc85e2a0eae57b3aae856eff32c4df0a4996
  Stored in directory: /home/mike/.cache/pip/wheels/5f/fd/9e/b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73
  Building wheel for gdown (pyproject.toml) ... done
  Created wheel for gdown: filename=gdown-3.12.2-py3-none-any.whl size=9674 sha256=a8f92d2e219dd25bc85f917f5e5cdbf5bfd3ba8753f8f7930868f31b119bcfae
  Stored in directory: /home/mike/.cache/pip/wheels/e2/62/1e/926d1ebe7b1e733c78d627fd288d01b83feaf67efc06e0e4c3
  Building wheel for mpld3 (setup.py) ... done
  Created wheel for mpld3: filename=mpld3-0.3-py3-none-any.whl size=116686 sha256=b4ecb5d9673cc060d659690b720838db99cbabb4e0339a1707d9301f5aa2422e
  Stored in directory: /home/mike/.cache/pip/wheels/3d/9f/9d/d806a20bd97bc7076d724fa3e69fa5be61836ba16b2ffa6126
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5567 sha256=c76c90012dd58a1fcf7826ad4be92b1cabfaaa88c68e56e23bc1f5d8a3b174c5
  Stored in directory: /home/mike/.cache/pip/wheels/cb/f3/5a/d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=ed4bd721de91451b090dd9e31ced07696d4c7cfca6445d0b3f602396d5d2e5ee
  Stored in directory: /home/mike/.cache/pip/wheels/56/ea/58/ead137b087d9e326852a851351d1debf4ada529b6ac0ec4e8c
  Building wheel for sqlitedict (setup.py) ... done
  Created wheel for sqlitedict: filename=sqlitedict-2.0.0-py3-none-any.whl size=15734 sha256=68064c06004c819ed85ffab311942f528c86a25c7b5c5cb2d5c49d1fd226ee1e
  Stored in directory: /home/mike/.cache/pip/wheels/ee/0b/8c/3cdf3e7eef4161d79c62df5bef35b0614238d0d2bd3051877a
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993225 sha256=09f49cf026b6cdf7d53cde07d5cebd86c515ad7700f003405e8420dd9ee04c74
  Stored in directory: /home/mike/.cache/pip/wheels/13/c7/b0/79f66658626032e78fc1a83103690ef6797d551cb22e56e734
  Building wheel for wikipedia-api (setup.py) ... done
  Created wheel for wikipedia-api: filename=Wikipedia_API-0.5.4-py3-none-any.whl size=13476 sha256=6df36bf132e194bb22c392f40433e64681c5df6a0c4946b250c675158304217a
  Stored in directory: /home/mike/.cache/pip/wheels/ed/88/e3/da3d4d73cb91d659488cfa25913b84bbc26febec99d257bce9
  Building wheel for overrides (setup.py) ... done
  Created wheel for overrides: filename=overrides-3.1.0-py3-none-any.whl size=10172 sha256=49e166626d2bb5c43c287b6a3d9fea8c9ed8449049f4911ea0350198972d51c1
  Stored in directory: /home/mike/.cache/pip/wheels/6a/4f/72/28857f75625b263e2e3f5ab2fc4416c0a85960ac6485007eaa
Successfully built torchfile bs4 gym networkx clang future iopath pyperclip termcolor wrapt gdown mpld3 word2number docopt sqlitedict langdetect wikipedia-api overrides
Failed to build python-Levenshtein
Installing collected packages: wrapt, word2number, wcwidth, typing-extensions, torchfile, tokenizers, termcolor, tensorflow-estimator, tensorboard-plugin-wit, sqlitedict, snowballstemmer, sentencepiece, pytz, pyperclip, pyglet, pyasn1, overrides, nlpaug, mpld3, lru-dict, keras, janome, ipython-genutils, iniconfig, flatbuffers, docopt, commonmark, clang, alabaster, zipp, xxhash, urllib3, traitlets, tqdm, torch, toml, threadpoolctl, terminaltables, tensorboard-data-server, tabulate, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, soupsieve, smart-open, six, setuptools, rsa, regex, PyYAML, python-magic, PySocks, pyparsing, pygments, pyDeprecate, pycparser, pyasn1-modules, py, protobuf, prompt_toolkit, portalocker, pluggy, pillow, orjson, oauthlib, numpy, num2words, multidict, more-itertools, MarkupSafe, lxml, llvmlite, konoha, kiwisolver, joblib, itsdangerous, imagesize, idna, gast, future, ftfy, fsspec, frozenlist, fonttools, filelock, editdistance, docutils, dill, deprecated, decorator, cycler, conllu, colorama, cloudpickle, click, charset-normalizer, cachetools, babel, attrs, async-timeout, yarl, Werkzeug, torchvision, tensorflow-hub, segtok, scipy, rich, requests, questionary, python-Levenshtein, python-dateutil, pyarrow, packaging, opt-einsum, numba, nltk, networkx, multiprocess, lemminflect, langdetect, keras-preprocessing, Jinja2, isodate, iopath, importlib-metadata, h5py, gym, grpcio, google-pasta, google-auth, contourpy, cmd2, cffi, beautifulsoup4, astunparse, aiosignal, absl-py, wikipedia-api, torchmetrics, sphinx, scikit-learn, requests-oauthlib, pytest, pandas, matplotlib, markdown, language-tool-python, hyperopt, huggingface-hub, gensim, flask, cryptography, bs4, azure-core, augly, aiohttp, transformers, sphinx-rtd-theme, msrest, lightgbm, google-auth-oauthlib, gdown, datasets, bpemb, adversarial-robustness-toolbox, tensorboard, flair, bert-score, azure-storage-blob, textattack, tensorflow, pytorch_lightning, tensorflow-text
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
  Running setup.py install for python-Levenshtein ... error
  error: subprocess-exited-with-error

  × Running setup.py install for python-Levenshtein did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      running install
      /home/mike/anaconda3/envs/counterfit/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/Levenshtein
      copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-3.8/Levenshtein
      copying Levenshtein/__init__.py -> build/lib.linux-x86_64-3.8/Levenshtein
      running egg_info
      writing python_Levenshtein.egg-info/PKG-INFO
      writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
      writing entry points to python_Levenshtein.egg-info/entry_points.txt
      writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
      writing requirements to python_Levenshtein.egg-info/requires.txt
      writing top-level names to python_Levenshtein.egg-info/top_level.txt
      reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*pyc' found anywhere in distribution
      warning: no previously-included files matching '*so' found anywhere in distribution
      warning: no previously-included files matching '.project' found anywhere in distribution
      warning: no previously-included files matching '.pydevproject' found anywhere in distribution
      adding license file 'COPYING'
      writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      copying Levenshtein/_levenshtein.c -> build/lib.linux-x86_64-3.8/Levenshtein
      copying Levenshtein/_levenshtein.h -> build/lib.linux-x86_64-3.8/Levenshtein
      running build_ext
      building 'Levenshtein._levenshtein' extension
      creating build/temp.linux-x86_64-3.8
      creating build/temp.linux-x86_64-3.8/Levenshtein
      gcc -pthread -B /home/mike/anaconda3/envs/counterfit/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mike/anaconda3/envs/counterfit/include/python3.8 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-3.8/Levenshtein/_levenshtein.o
      unable to execute 'gcc': No such file or directory
      error: command 'gcc' failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-Levenshtein

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by mikemishal** [comment]
using conda install -c conda-forge python-levenshtein solved the issue for me.

**Comment by dlmgary** [comment]
Hi @mikemishal, we've made some changes to the repository. Can you check from the latest version of `main` and see if that fixes the issue?

**Comment by mikemishal** [comment]
I tried running it again and received the same error, it is attempting to install python-levenshtein as a pip install. 


Building wheels for collected packages: python-Levenshtein, gym, counterfit, livereload
  Building wheel for python-Levenshtein (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/__init__.py -> build/lib.linux-x86_64-cpython-38/Levenshtein
      running egg_info
      writing python_Levenshtein.egg-info/PKG-INFO
      writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
      deleting python_Levenshtein.egg-info/entry_points.txt
      writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
      writing requirements to python_Levenshtein.egg-info/requires.txt
      writing top-level names to python_Levenshtein.egg-info/top_level.txt
      reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*pyc' found anywhere in distribution
      warning: no previously-included files matching '*so' found anywhere in distribution
      warning: no previously-included files matching '.project' found anywhere in distribution
      warning: no previously-included files matching '.pydevproject' found anywhere in distribution
      adding license file 'COPYING'
      writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      copying Levenshtein/_levenshtein.c -> build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/_levenshtein.h -> build/lib.linux-x86_64-cpython-38/Levenshtein
      running build_ext
      building 'Levenshtein._levenshtein' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/Levenshtein
      gcc -pthread -B /home/mike/anaconda3/envs/counterfit/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mike/anaconda3/envs/counterfit/include/python3.8 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-cpython-38/Levenshtein/_levenshtein.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-Levenshtein
  Running setup.py clean for python-Levenshtein
  Building wheel for gym (pyproject.toml) ... done
  Created wheel for gym: filename=gym-0.26.2-py3-none-any.whl size=827636 sha256=9eda03a86a88eb47c6a8701f5bd6a6e7a2381122c33254d7cd01e592e5f8a880
  Stored in directory: /home/mike/.cache/pip/wheels/17/79/65/7afedc162d858b02708a3b8f7a6dd5b1000dcd5b0f894f7cc1
  Building wheel for counterfit (setup.py) ... done
  Created wheel for counterfit: filename=counterfit-1.1.0-py3-none-any.whl size=333889195 sha256=ad07fcbf4b5c8de7b30307e5de6c21561827030e0597a76f26e6a201c4e775ae
  Stored in directory: /tmp/pip-ephem-wheel-cache-tcuebaf0/wheels/7f/3a/e0/fda2d9c83018685af0e51bdeb809c3c6a6feee000287cb624e
  Building wheel for livereload (setup.py) ... done
  Created wheel for livereload: filename=livereload-2.6.3-py2.py3-none-any.whl size=24707 sha256=2822e1cd7edbc62c1531fb57d1a324d60eb37e0920039cb1ca46a0695d0a1fff
  Stored in directory: /home/mike/.cache/pip/wheels/48/d7/34/372e0521bd5c9f6dcdff307e37ef6f9c00c1e1e2afc9707b5c
Successfully built gym counterfit livereload
Failed to build python-Levenshtein
Installing collected packages: word2number, webencodings, wcwidth, torchfile, tokenizers, tensorboard-plugin-wit, sqlitedict, snowballstemmer, sentencepiece, pytz, pyperclip, pyglet, pyasn1, overrides, nlpaug, mpld3, mistune, lru-dict, libclang, keras, janome, iniconfig, gym-notices, flatbuffers, fastjsonschema, docopt, distlib, commonmark, chardet, alabaster, zipp, xxhash, wrapt, urllib3, typing-extensions, traitlets, tqdm, tornado, toml, tinycss2, threadpoolctl, terminaltables, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, tabulate, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, soupsieve, smart-open, six, rsa, regex, pyzmq, pyyaml, python-magic, python-Levenshtein, PySocks, pyrsistent, pyparsing, pygments, pygame, pyDeprecate, pycparser, pyasn1-modules, py, protobuf, prompt_toolkit, PrettyTable, portalocker, pluggy, platformdirs, pkgutil-resolve-name, pillow, pbr, pandocfilters, orjson, oauthlib, numpy, num2words, nodeenv, nest-asyncio, multidict, more-itertools, MarkupSafe, lxml, llvmlite, konoha, kiwisolver, jupyterlab-pygments, joblib, itsdangerous, imagesize, idna, identify, greenlet, gast, future, ftfy, fsspec, frozenlist, fonttools, filelock, entrypoints, editdistance, docutils, dill, defusedxml, decorator, cycler, conllu, colorlog, colorama, cloudpickle, click, charset-normalizer, cfgv, cachetools, babel, autopage, attrs, async-timeout, absl-py, yarl, Werkzeug, virtualenv, torch, tensorflow-hub, tensorboardX, stevedore, sqlalchemy, segtok, scipy, rich, requests, questionary, python-dateutil, pyarrow, packaging, opt-einsum, onnxruntime, nltk, networkx, multiprocess, Mako, livereload, lemminflect, langdetect, keras-preprocessing, jupyter-core, Jinja2, isodate, iopath, importlib-resources, importlib-metadata, h5py, grpcio, google-pasta, google-auth, deprecated, contourpy, cmd2, cmaes, cffi, bleach, beautifulsoup4, astunparse, aiosignal, wikipedia-api, torchvision, torchmetrics, sphinx, scikit-learn, requests-oauthlib, pytest, pre-commit, pandas, numba, matplotlib, markdown, language-tool-python, jupyter-client, jsonschema, hyperopt, huggingface-hub, gym, gensim, flask, cryptography, cmd2-ext-test, cliff, bs4, azure-core, augly, alembic, aiohttp, transformers, sphinx-rtd-theme, sphinx-markdown-tables, sphinx-copybutton, sphinx-autobuild, recommonmark, optuna, nbformat, msrest, lightgbm, google-auth-oauthlib, gdown, datasets, bpemb, adversarial-robustness-toolbox, tensorboard, nbclient, flair, bert-score, azure-storage-blob, textattack, tensorflow, pytorch_lightning, nbconvert, tensorflow-text, nbsphinx, counterfit
  Running setup.py install for python-Levenshtein ... error
  error: subprocess-exited-with-error

  × Running setup.py install for python-Levenshtein did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      running install
      /home/mike/anaconda3/envs/counterfit/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/__init__.py -> build/lib.linux-x86_64-cpython-38/Levenshtein
      running egg_info
      writing python_Levenshtein.egg-info/PKG-INFO
      writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
      writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
      writing requirements to python_Levenshtein.egg-info/requires.txt
      writing top-level names to python_Levenshtein.egg-info/top_level.txt
      reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*pyc' found anywhere in distribution
      warning: no previously-included files matching '*so' found anywhere in distribution
      warning: no previously-included files matching '.project' found anywhere in distribution
      warning: no previously-included files matching '.pydevproject' found anywhere in distribution
      adding license file 'COPYING'
      writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
      copying Levenshtein/_levenshtein.c -> build/lib.linux-x86_64-cpython-38/Levenshtein
      copying Levenshtein/_levenshtein.h -> build/lib.linux-x86_64-cpython-38/Levenshtein
      running build_ext
      building 'Levenshtein._levenshtein' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/Levenshtein
      gcc -pthread -B /home/mike/anaconda3/envs/counterfit/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mike/anaconda3/envs/counterfit/include/python3.8 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-cpython-38/Levenshtein/_levenshtein.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-Levenshtein

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by dlmgary** [comment]
@mikemishal, it looks like it's trying to install python-levenshtein from source but your environment is missing `gcc`. 

Can you run `sudo apt update && sudo apt install build-essential` to install the build essentials (this should install gcc) and then retry the Counterfit installation? 

Let me know if that fixes the issue and I'll create a PR to update the documentation! 👍

**Comment by mikemishal** [comment]
That worked thank you.
