### ISSUE TITLE
Parsing issue in scan.

### ISSUE THREAD

**Issue by erickgalinkin** [Azure/counterfit#9]
When attempting to scan using the `-a` option with multiple attacks, the script only launches the last attack. 

I am using a tensorflow model trained on mnist. I've attached images displaying the issue.
The issue occurs with both the "image" and "numpy" `model_data_type`.

![Screen Shot 2021-05-20 at 9 59 57 AM](https://user-images.githubusercontent.com/43585941/118993066-322a7700-b953-11eb-842b-22d7c39c0303.png)

![Screen Shot 2021-05-20 at 9 56 18 AM](https://user-images.githubusercontent.com/43585941/118993015-263eb500-b953-11eb-9e6f-56cc6a20af59.png)

**Comment by moohax** [comment]
Thanks Eric. 

Found that we added `nargs+` to `--attack` but didn't implement the logic to actually execute on every attack...

**Comment by moohax** [comment]
This has been fixed in the competition branch (`docker run -p8888:8888 azuretrustworthyml/counterfit-mlsecevasion:latest`). We will backport to main, but this has some additional attacks that you would probably be interested in.
